# Generated by Django 6.0.7 on 2026-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crop_images/')),
                ('disease_name', models.CharField(default='Unknown', max_length=100)),
                ('treatment', models.TextField(default='No treatment available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
